### ISSUE TITLE
Restock Villager

### ISSUE THREAD

**Issue by alechretien16** [RebelMythik/AntiVillagerLag#33]
Server: 1.19.2
Software: Purpur #1784

The bug I'm getting is that villagers don't reset their trades. It happens a few weeks ago but since few of my users have this active, it was not noticeable.

Console error:
[18:36:55 ERROR]: Could not pass event PlayerInteractEntityEvent to AntiVillagerLag v2.1.1
java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 78
        at java.lang.String.checkBoundsBeginEnd(String.java:4601) ~[?:?]
        at java.lang.String.substring(String.java:2704) ~[?:?]
        at rebelmythik.antivillagerlag.utils.VillagerUtilities.replaceText(VillagerUtilities.java:59) ~[AntiVillagerLag-2.1.1.jar:?]
        at rebelmythik.antivillagerlag.events.RestockVillager.restockMessage(RestockVillager.java:35) ~[AntiVillagerLag-2.1.1.jar:?]
        at rebelmythik.antivillagerlag.events.RestockVillager.call(RestockVillager.java:94) ~[AntiVillagerLag-2.1.1.jar:?]
        at rebelmythik.antivillagerlag.events.EventListenerHandler.rightClick(EventListenerHandler.java:101) ~[AntiVillagerLag-2.1.1.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor56.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:git-Purpur-1784]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$6.performInteraction(ServerGamePacketListenerImpl.java:3006) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$6.a(ServerGamePacketListenerImpl.java:3063) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$InteractionAction.dispatch(ServerboundInteractPacket.java:131) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2998) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.2.jar:git-Purpur-1784]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1388) ~[purpur-1.19.2.jar:git-Purpur-1784]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[purpur-1.19.2.jar:git-Purpur-1784]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1365) ~[purpur-1.19.2.jar:git-Purpur-1784]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1358) ~[purpur-1.19.2.jar:git-Purpur-1784]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1492) ~[purpur-1.19.2.jar:git-Purpur-1784]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[purpur-1.19.2.jar:git-Purpur-1784]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1784]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by D-VR** [comment]
please update to the newest version of AVL and see if the issue persists then 

https://www.spigotmc.org/resources/antivillagerlag.102949/

**Comment by RebelMythik** [comment]
Could you provide your messages part of the config file as well?

**Comment by alechretien16** [comment]
> please update to the newest version of AVL and see if the issue persists then
> 
> https://www.spigotmc.org/resources/antivillagerlag.102949/

It works thank you!! I don't know why I thought I had the latest version, I was 2 updates behind!
